### ISSUE TITLE
Transitions while changing the block size

### ISSUE THREAD

**Issue by usulpro** [BosNaufal/react-scrollbar#5]
noticeable that scrollbar reaction is delayed when resizing windows (see horizontal scrollbar in Demo)

**Comment by BosNaufal** [comment]
@UsulPro When window size has changed, react scrollbar calculates for the next width but it is waiting for mouse interaction inside of it to resize its scrollbar (horizontal/vertical). Because the calculation of scrollbar length will happen when it got an interaction. 

I have no Idea to have a better solution. Have you any?

**Comment by usulpro** [comment]
Yes, I'm working on it [this branch](https://github.com/UsulPro/react-scrollbar-js/commits/css_themes)
the point is that it is necessary to left css transition only for scrolling by mouse wheel
when all else is ready I will PR
